# -*- coding: utf-8 -*-
"""AIML01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cPtZ38l9tx7mLBnK3WBBd70fshxq69EN
"""

class SimpleChatbot:
    def __init__(self):
        self.context = {}

    def greet(self):
        return "Helloo There! I'm AskMe , your friendly chatbot. Hope you're doing great!\n How can I assist you today?\n"

    def farewell(self):
        return "Goodbye! Have a great day! See you again!\n"

    def respond_to_question(self, question):
        question = question.lower()
        if "your name" in question:
            return "I am AskMe, an AI chatbot.\n"
        elif "how are you" in question:
            return " Ahh I'm just a bunch of code.. but thats very kind of you for asking!\n How can I help you?\n"
        elif "weather" in question:
            return "I can't check the weather, but I hope it's nice where you are!\n"
        elif "age" in question:
            return "I don't have an age, but I was created in 2024\n."
        elif "help" in question:
            return "Sure, I'm here to help! What do you need assistance with?\n"
        else:
            return self.handle_error()

    def handle_error(self):
        return "I'm sorry, I didn't understand that. Could you please rephrase your question?\n"

    def remember_context(self, user_input):
        self.context['last_interaction'] = user_input

    def recall_context(self):
        if 'last_interaction' in self.context:
            return f"You mentioned '{self.context['last_interaction']}' earlier."
        return "I don't recall anything from our previous conversations."

    def ask_questions(self):
        questions = [
            "What is your name?",
            "How are you feeling today?",
            "What can I do for you?"
        ]
        user_responses = []
        for question in questions:
            print(question)
            response = input()
            user_responses.append(response)
            self.remember_context(response)
            print(f"Thanks for sharing that! {self.recall_context()}")
        return user_responses

def main():
    chatbot = SimpleChatbot()
    print(chatbot.greet())

    while True:
        user_input = input("You: ")
        if user_input.lower() in ["bye", "exit", "quit"]:
            print(chatbot.farewell())
            break
        else:
            response = chatbot.respond_to_question(user_input)
            print(f"Chatbot: {response}")
            chatbot.remember_context(user_input)

if __name__ == "__main__":
    main()